cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'homebrew/cask'

brew 'ansible'
brew 'ansible-lint'
brew 'bash'
brew 'bash-completion'
brew 'cmake'
brew 'coreutils'
brew 'curl'
brew 'docker-completion'
brew 'exiftool'
brew 'git'
brew 'git-extras'
brew 'git-sizer'
brew 'hub'
brew 'htop-osx'
brew 'imagemagick'
brew 'jq'
brew 'kubectx'
brew 'kubernetes-cli'
brew 'lesspipe'
brew 'libdvdcss'
brew 'nmap'
brew 'nvm'
brew 'postgresql@9.6'
brew 'python3'
brew 'redis'
brew 'ripgrep'
brew 'shellcheck'
brew 'spark'
brew 'sqlite'
brew 'ssh-copy-id'
brew 'tree'
brew 'v8'
brew 'wget'
brew 'yarn'
brew 'yarn-completion'

# brew cask recipes
cask 'docker'
cask 'macvim'
cask 'sourcetree'

# oracle instant client
brew 'InstantClientTap/instantclient/instantclient-basiclite'
brew 'drone/drone/drone'
