# see https://direnv.net/man/direnv.toml.1.html

[global]

# Also look for and load .env files on top of the .envrc files.
# If both .envrc and .env files exist, the .envrc will always be chosen first.
load_dotenv = true


# If set to true, the .envrc will be loaded with set -euo pipefail.
# This option will be the default in the future.
strict_env = true

# Specify how long to wait before warning the user that the command is taking too long to execute. 
# Defaults to “5s”.
warn_timeout = "2s"
